In [30]:
import numpy as np

In [31]:
#x,y correspond to AND
#=>2 units(and 1 bias unit) in input layer and 1 unit in output layer
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([0,0,0,1]).reshape(-1,1)

In [32]:
def sig(z):
    return (1/(1+np.exp(-z)))

In [33]:
weights=2*np.random.random((2,1))-1    #will make an array 2*1, each entry will be filled by a random no. between -1 and 1
bias=2*np.random.random(1)-1           #2 units in input layer going to 1 unit in output, therefore (2,1)
print(weights)
print()
print(bias)

[[ 0.30857618]
 [-0.69002073]]

[-0.6176541]


In [34]:
out0=x                                 #output of 0th(input) layer(same as input data)
out=sig(np.dot(x,weights)+bias)        #final output(y_pred)
out
#see that outputs are all predicting 0. This is because weights are flawed. We need to apply back propagation and minimize
#error to get to the optimal weights

array([[0.35031518],
       [0.21287619],
       [0.42333982],
       [0.26911868]])

In [35]:
alpha=0.1                                                              #learning rate
slope=np.array([[0],[0]])                                              #initializing slope array with dummy values. (value in 00 will store slope corresponding to weight W11 and 10 will store slope corresponding to W21)

In [44]:
for iter in range(10000):                                            #running gradient descent fot 10000 iterations
    first_term=out-y                                                 #see notes(handwritten)
    second_term=out*(1-out)                                          #see notes(handwritten)
    third_term=out0                                                  #the third term is Oi, so we need to multiply first and second term with Oi to get dinputj/dwij, and then sum it over all training data points. See that Oi is same as x1 or x2. for dinputj/dw1j, we need x1 and for dinputj/dw2j, we need x2. We are going to store the values of dinputj/dwij and dinputj/dw2j in slope aray (2*1) and use this for gradient descent
    slope=np.dot(third_term.T,(first_term*second_term))              #.T means transpose
    weights=weights-(alpha*slope)                                    #updating weights, using gradient descent, alpha is the learning rate
    bias=bias-alpha*(first_term*second_term).sum()                   #change for bias
    out=sig(np.dot(x,weights)+bias)                                  #getting the output, for these new weights
out                                                                  #see that output is very good now

array([[6.47429535e-06],
       [1.72882391e-02],
       [1.72882391e-02],
       [9.79509398e-01]])