In [1]:
import numpy as np
import pandas as pd

In [2]:
train=pd.read_csv("Train.csv").values
test=pd.read_csv("Test.csv").values

In [3]:
x_train=train[:,:-1]
y_train=train[:,-1].flatten()
x_test=test

x_train.shape,y_train.shape,x_test.shape

((1600, 5), (1600,), (400, 5))

In [4]:
class LOWESS():
    def __init__(self):
        pass
    
    def weights(self,x_train,x,bw):                              #x is one query point(1 test sample from the entire test set)
        return np.e**(-(((x_train-x)**2).sum(axis=1)/(2*bw*bw)))        #numpy array containing Wi for all i (training examples)
    
    def theta(self,x_train,y_train,x,bw):                   #x is one query point(1 test sample from the entire test set)
        
        w=self.weights(x_train,x,bw)                        #1d array of weights for each i (trainng examples)
        print(w)
        w=w.reshape(-1,1)                                   #converting to column major form (multiple rows,1 col)
        
        thetas=np.dot(np.linalg.inv(np.dot(x_train.T,(w*x_train))),np.dot(x_train.T,w*(y_train.reshape(-1,1))))
        
        return thetas
    
    def predict(self,x_train,y_train,x_test,bw):
        predictions=[]
        
        for test_j in x_test:                               #test_j denotes 1 query point(test sample)
            params=self.theta(x_train,y_train,test_j,bw)    #params is an array (multiple rows(N),1 column)
            
            prediction=np.dot(test_j,params.flatten())
            
            predictions.append(prediction)
            
        return np.array(predictions)

In [5]:
reg=LOWESS()
reg

In [14]:
predictions=reg.predict(x_train,y_train,x_test,5)

[0.67132745 0.76839474 0.74456138 ... 0.7383699  0.68661464 0.51919147]
[0.88665247 0.86093232 0.96705712 ... 0.75679096 0.85880885 0.76813249]
[0.81011648 0.95750515 0.829959   ... 0.78161318 0.87251377 0.79223213]
[0.7345298  0.83480229 0.80025836 ... 0.66320388 0.85555691 0.73458524]
[0.912762   0.89641473 0.89574826 ... 0.9243027  0.95874108 0.78159471]
[0.82573899 0.81990712 0.83473208 ... 0.95256002 0.95879969 0.6556369 ]
[0.89832266 0.82789074 0.91900551 ... 0.71512491 0.80341394 0.80349103]
[0.80207007 0.92626076 0.86378783 ... 0.69567395 0.82886402 0.79406638]
[0.83959973 0.82679147 0.92729855 ... 0.72265624 0.85858596 0.74588838]
[0.86298136 0.79935764 0.95011573 ... 0.72526301 0.70539344 0.66244082]
[0.88501951 0.95431113 0.88888091 ... 0.85830024 0.94883624 0.82419769]
[0.92893424 0.9855686  0.91377194 ... 0.77308165 0.83082835 0.90519023]
[0.95524489 0.88558137 0.98505166 ... 0.76749699 0.78299815 0.80496616]
[0.83369256 0.7936835  0.91079025 ... 0.85194813 0.8759415  0.63

[0.90531553 0.83293562 0.96427391 ... 0.75655853 0.76305214 0.73137613]
[0.87201359 0.88737404 0.88989677 ... 0.95223618 0.90538291 0.68397129]
[0.94250789 0.84642683 0.93901679 ... 0.7236592  0.6686866  0.77336731]
[0.81093413 0.86641391 0.87856462 ... 0.83831282 0.93428928 0.69810979]
[0.86399233 0.84147267 0.88371366 ... 0.81350222 0.91043851 0.76680753]
[0.86855034 0.91901051 0.84840403 ... 0.73259683 0.84290783 0.88579924]
[0.86812469 0.77499981 0.91829686 ... 0.79492168 0.80647964 0.67715406]
[0.88889648 0.97069    0.87656054 ... 0.78557651 0.85149399 0.85998652]
[0.79248838 0.82593731 0.84547568 ... 0.73523175 0.82948673 0.70055795]
[0.80416512 0.81464847 0.82035623 ... 0.64779345 0.76898553 0.78077158]
[0.94312403 0.97886637 0.92253785 ... 0.77407225 0.81914824 0.90749748]
[0.87300406 0.91269509 0.88806575 ... 0.6857711  0.73658731 0.82552095]
[0.91758964 0.88731797 0.87716156 ... 0.66113962 0.77793781 0.95912977]
[0.91281658 0.9318797  0.93304926 ... 0.70222068 0.76311558 0.86

[0.85174946 0.9129106  0.91385745 ... 0.6790496  0.75975122 0.80521618]
[0.80314891 0.87945932 0.86285266 ... 0.85767119 0.94492648 0.69243821]
[0.87029291 0.87468289 0.84741016 ... 0.89583708 0.93949112 0.75836612]
[0.96192682 0.95540456 0.96424076 ... 0.79695775 0.89348384 0.90802961]
[0.8306095  0.91243427 0.88271011 ... 0.71022482 0.8172576  0.79120419]
[0.92579949 0.938818   0.9283675  ... 0.79949011 0.86097111 0.84786739]
[0.85025157 0.75968325 0.89103857 ... 0.54155418 0.62955852 0.80101462]
[0.94633562 0.79549348 0.89793721 ... 0.78667612 0.67155041 0.72076855]
[0.90621497 0.86107041 0.88746331 ... 0.9364662  0.93471591 0.74344259]
[0.83497566 0.74995388 0.82263406 ... 0.77724616 0.83248436 0.70274644]
[0.86624723 0.85539785 0.82673844 ... 0.62936451 0.72348372 0.89058516]
[0.97319769 0.89358188 0.99365911 ... 0.78222575 0.80161633 0.8258689 ]
[0.90216441 0.92537331 0.80160467 ... 0.79902205 0.82730019 0.90028233]
[0.83773693 0.78168126 0.93851594 ... 0.73509833 0.81422556 0.67

In [12]:
d={"Id":np.arange(0,predictions.shape[0]),"target":predictions}
df=pd.DataFrame(d)
df.to_csv("submission.csv",index=False)